---
title: "MakingBuoyGraphs"
output: html_document
date: "2024-07-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#EXO Temp Plot
```{r EXO Temp Plot}
ggplot(data = exocleaned,
        mapping = aes(x = datetime, y = waterTemperature_EXO_degC_1m)) +
  theme_bw() +
  scale_x_discrete(breaks=c("2021-07-01 00:00:00","2021-08-01 00:00:00",
                            "2021-09-01 00:00:00","2021-10-01 00:00:00",
                            "2022-04-26 11:10:00","2022-05-01 00:00:00",
                            "2022-06-01 00:00:00","2022-07-01 00:00:00",
                            "2022-08-01 00:00:00","2022-09-01 00:00:00",
                            "2022-10-01 00:00:00"),
                   labels=c("July 2021","Aug 2021","Sept 2021","Oct 2021",
                            "Buoy Offline","May 2022","June 2022",
                            "July 2022","Aug 2022","Sept 2022","Oct 2022")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_point(shape = 19, size = .7,
             aes(color = waterTemperature_EXO_degC_1m),
             show.legend = FALSE) +
  labs(title = "Water Temperature at 1m \nLoon Island July 2021 - October 2022",
       y = "Water Temperature (°C)", 
       caption = "*Buoy overwintered in harbor from 19 Oct 2021 to 26 Apr 2022") +
  theme(text = element_text(family="Futura"),
        axis.title.x = element_blank(), 
        plot.title = element_text(hjust=0.5)) +
  geom_vline(xintercept = 15913, lwd = 0.8, color = "darkgray") +
  scale_color_gradient2(low = "#67c9ff",midpoint = 17.5, 
                        mid = "#D5BCE8", high = "#F92929")

```

#EXO Chlorophyll Plot
```{r EXO Chlorophyll Fluorescence}
ggplot(data = exo_cleaned,
       mapping = aes(x = datetime, y = chlorophyllFluorescence_RFU_1m)) +
  theme_bw() +
  scale_x_discrete(breaks=c("2021-07-01 00:00:00","2021-08-01 00:00:00",
                            "2021-09-01 00:00:00","2021-10-01 00:00:00",
                            "2022-04-26 11:10:00","2022-05-01 00:00:00",
                            "2022-06-01 00:00:00","2022-07-01 00:00:00",
                            "2022-08-01 00:00:00","2022-09-01 00:00:00",
                            "2022-10-01 00:00:00"),
                   labels=c("July 2021","Aug 2021","Sept 2021","Oct 2021",
                            "Buoy Offline","May 2022","June 2022",
                            "July 2022","Aug 2022","Sept 2022","Oct 2022")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_point(shape = 19, size = .7, 
             aes(color = chlorophyllFluorescence_RFU_1m),
             show.legend = FALSE) +
  labs(title = "Chlorophyll at 1m \nLoon Island July 2021 - October 2022", 
       y = "Chlorophyll Fluorescence (RFU)", 
       caption = "*Buoy overwintered in harbor from 19 Oct 2021 to 26 Apr 2022") +
  theme(text = element_text(family="Futura"),
        axis.title.x = element_blank(), 
        plot.title = element_text(hjust=0.5)) +
  geom_vline(xintercept = 15913, lwd = 0.8, color = "darkgray") +
  scale_color_gradient2(low = "#F92929", midpoint = 0.2, 
                        mid = "#E9C472", high = "#068E4C")
```

#EXO DO Plot
```{r EXO DO Plot}
ggplot(data = exo_cleaned,
       mapping = aes(x = datetime, y = oxygenDissolved_mgl_1m)) +
  theme_bw() +
  scale_x_discrete(breaks=c("2021-07-01 00:00:00","2021-08-01 00:00:00",
                            "2021-09-01 00:00:00","2021-10-01 00:00:00",
                            "2022-04-26 11:10:00","2022-05-01 00:00:00", 
                            "2022-06-01 00:00:00","2022-07-01 00:00:00",
                            "2022-08-01 00:00:00","2022-09-01 00:00:00",
                            "2022-10-01 00:00:00"),
                   labels=c("July 2021","Aug 2021","Sept 2021","Oct 2021",
                            "Buoy Offline","May 2022","June 2022",
                            "July 2022","Aug 2022","Sept 2022","Oct 2022")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_point(shape = 19, size = .7, 
             aes(color = oxygenDissolved_mgl_1m), 
             show.legend = FALSE) +
  labs(title = "Dissolved Oxygen at 1m \nLoon Island July 2021 - October 2022",
       y = "Disolved Oxygen (mg/L)", 
       caption = "*Buoy overwintered in harbor from 19 Oct 2021 to 26 Apr 2022") +
  theme(text = element_text(family="Futura"),
        axis.title.x = element_blank(), 
        plot.title = element_text(hjust=0.5)) +
  geom_vline(xintercept = 15913, lwd = 0.8, color = "darkgray") +
  scale_color_gradient2(low = "#F90327", midpoint = 9, 
                        mid = "#A7D4ED", high = "#0C89F4")
```

